final

diff --git a/BackSprint/Dockerfile b/BackSprint/Dockerfile
--- a/BackSprint/Dockerfile
+++ b/BackSprint/Dockerfile
@@ -1,10 +1,10 @@
-FROM --platform=$BUILDPLATFORM maven:3.8.5-eclipse-temurin-17 AS builder
+FROM --platform=$BUILDPLATFORM maven:3.9.7-eclipse-temurin-21 AS builder
 WORKDIR /workdir/server
 COPY pom.xml /workdir/server/pom.xml
 RUN mvn dependency:go-offline
-
 COPY src /workdir/server/src
-RUN mvn install
+
+RUN mvn install || { echo 'Maven build failed'; exit 1; }
 
 FROM builder as dev-envs
 
@@ -27,7 +27,7 @@ RUN mkdir -p target/dependency
 WORKDIR /workdir/server/target/dependency
 RUN jar -xf ../*.jar
 
-FROM eclipse-temurin:17-jre-focal
+FROM eclipse-temurin:21-jre
 
 EXPOSE 8080
 VOLUME /tmp
@@ -35,4 +35,4 @@ ARG DEPENDENCY=/workdir/server/target/dependency
 COPY --from=prepare-production ${DEPENDENCY}/BOOT-INF/lib /app/lib
 COPY --from=prepare-production ${DEPENDENCY}/META-INF /app/META-INF
 COPY --from=prepare-production ${DEPENDENCY}/BOOT-INF/classes /app
-ENTRYPOINT ["java","-cp","app:app/lib/*","com.company.project.Application"]
+ENTRYPOINT ["java","-cp","app:app/lib/*","APIFourparks.Backend.Login.AuthApplication"]
